- .github/workflows/create-release-pr.yml
- .github/workflows/main.yml
- .github/workflows/publish-release.yml
- .github/workflows/publish-site.yml
- gatsby-config.ts
- package.json
- static/CNAME
- yarn.lock
This pull request adds a couple workflows to release and deploy the directory to GitHub Pages.
> Set up deployment to GitHub Pages

- gatsby-node.ts
- src/components/SnapCard.tsx
- src/components/providers/SnapsProvider.tsx
Use descriptions and summaries defined in the registry.
> Use descriptions and summaries from registry

- src/components/FilterMenu.tsx
- src/components/FooterLinks.tsx
- src/components/SnapsGrid.tsx
- src/components/providers/SnapsProvider.tsx
This fixes a couple errors related to keys.
> Fix invalid React keys

- src/components/InstallSnapButton.tsx
- src/components/PostInstallModal.tsx
- src/locales/en/messages.po
- src/pages/snap/{Snap.location}/{Snap.slug}.tsx
The website was missing in the post install modal.
> Fix missing website on post install modal

- gatsby-config.ts
- src/pages/index.tsx
- src/types/vendor/react-use-fusejs.d.ts
Improve search by matching on summary and reducing the Fuse threshold.
> Improve search

- src/components/BackButton.tsx
- src/components/InstallSnapButton.tsx
- src/components/InstallUnsupported.tsx
- src/components/InstallUnsupportedDesktop.tsx
- src/components/SnapAuthorship.tsx
- src/components/SnapCard.tsx
- src/components/SnapData.tsx
- src/pages/snap/{Snap.location}/{Snap.slug}.tsx
💅 fine-tuned hover states, typography, margins, etc.
> Design details

- package.json
- yarn.lock
Add resolution for `xml2js` to resolve https://github.com/MetaMask/snaps-directory/security/dependabot/1
> Bump `xml2js`

- gatsby-config.ts
- package.json
- yarn.lock
This adds `gatsby-plugin-robots-txt` to generate a `robots.txt` file.
> Generate robots.txt file

- src/locales/en/messages.po
- src/pages/index.tsx
This PR updates the copy on the homepage.
> Update copy on the homepage

- src/@chakra-ui/gatsby-plugin/theme.js
- src/components/FooterLinks.tsx
- src/components/SnapAuthorship.tsx
- src/components/SnapData.tsx
- src/pages/404.tsx
- src/pages/index.tsx
- src/pages/snap/{Snap.location}/{Snap.slug}.tsx
I've updated all font values to use "Euclid Circular B," with a fallback to the system fonts. This also means we can remove the "custom" font value.
> Small polishing changes

- src/components/Card.tsx
- src/components/Footer.tsx
- src/components/Header.tsx
- src/components/Layout.tsx
- src/features/filter/components/FilterSearch.tsx
- src/pages/snap/{Snap.location}/{Snap.slug}.tsx
- src/theme/semantic-tokens.ts
This adds a header that sticks to the top.
> Add sticky header

- gatsby-node.ts
This hides Snaps without a category.
> Hide Snaps without a category

- gatsby-node.ts
- package.json
- yarn.lock
This hides Snaps with `hidden` set to `true`, which we use for example Snaps.
> Hide Snaps with hidden field

- src/components/Footer.tsx
- src/components/FooterCopyright.tsx
- src/components/FooterTerms.tsx
This makes the footer text a bit easier to read.
Closes #180.
> Update footer text colour

- gatsby-config.ts
Adds the extended descriptions to the data passes to FuseJS for searching.
> Search using descriptions

- yarn.lock
Remove vulnerable babel/traverse by deduping dependencies and bumping depcheck.
> Remove vulnerable babel/traverse

- src/components/SnapAvatar.tsx
Remove the snap avatar scaling hack as it is not needed following #223
> Remove snap avatar scaling

- gatsby-node.ts
Support localized manifests by resolving to the English translation for now.
> Support localized manifests

- src/components/SnapCategory.test.tsx
- src/components/icons/index.ts
- src/constants.ts
- src/features/filter/Filter.test.tsx
- src/features/filter/components/FilterCategory.test.tsx
- src/features/filter/components/FilterTag.test.tsx
- src/features/filter/components/FilterTags.test.tsx
- src/features/filter/components/FilterTags.tsx
- src/features/filter/constants.tsx
- src/locales/en/messages.po
- src/pages/index.tsx
- src/pages/{Category.name}/index.test.tsx
- src/pages/{Category.name}/installed.test.tsx
Adds a tag to display the currently selected sorting mode.
Also updates copy for the categories used in the directory. "Transaction Insights" is now called "Security" and "Notifications" is now called "Communication".
> Add sorting tag and tweak copy

- src/components/SnapAuthorship.tsx
- src/components/SnapAvatar.tsx
Fixes the responsiveness on the snap profile page header.
> Fix responsiveness on profile page header

- gatsby-node.ts
Adds verification of the registry signature before continuing the building process.
> Verify registry signature before building

- src/components/InstallationCount.test.tsx
- src/components/InstallationCount.tsx
- src/components/SnapAvatar.tsx
- src/components/index.ts
- src/features/snap/components/Authorship.tsx
- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/locales/ja-JP/messages.po
- src/locales/pt-BR/messages.po
- src/locales/ru-RU/messages.po
- src/locales/tr-TR/messages.po
- src/locales/zh-CN/messages.po
- src/pages/snap/{Snap.location}/{Snap.slug}.tsx
Show installation numbers on the Snap profile page.
Closes https://github.com/MetaMask/snaps-directory/issues/373
> Show installation counts

- src/pages/snap/{Snap.location}/{Snap.slug}.tsx
Display install numbers even when the Snap is installed.
> Display install numbers when installed
