- src/components/SnapData.tsx
- src/pages/snap/{Snap.location}/{Snap.slug}.tsx
This PR will add UI optimizations so the information on the Snap page can be readable on medium size screens.
> Add UI improvements for medium screens on a Snap info page

- src/components/InstallSnapButton.tsx
- src/components/InstallUnsupported.tsx
The button is duplicated, but not all of them had the same styling applied to them.
We should find a better way to do this.
> Fix installation button responsiveness

- .github/workflows/publish-site.yml
- .github/workflows/republish-release.yml
When the registry is updated, we want to be able to redeploy the website without having to cut a release. I've added a new workflow which can be triggered through the GitHub API (or manually), and uses the latest tag to redeploy the website.
> Add workflow for redeploying the website

- .github/workflows/republish-release.yml
`actions/checkout` only fetches a single commit by default. In order to get tags we need to set `fetch-depth: 0`.
> Add fetch-depth: 0 to fetch tags

- src/components/Card.tsx
- src/components/LoadingCard.tsx
- src/components/LoadingGrid.tsx
- src/components/SnapCard.tsx
- src/components/index.ts
- src/pages/index.tsx
This adds a grid with six skeleton cards as fallback, before the snap cards are loaded.
> Add skeleton loader fallback

- src/components/SnapDescription.tsx
- src/pages/snap/{Snap.location}/{Snap.slug}.tsx
Previously, newlines (`\n`) were ignored.
> Keep newlines in snap descriptions

- .github/workflows/publish-site.yml
Instead of using the standard GitHub token, we want to use a personal access token, so we can properly protect the `gh-pages` branch.
Fixes #73
> Deploy to GitHub Pages using personal token

- src/pages/snap/{Snap.location}/{Snap.slug}.tsx
- src/utils/links.ts
Replace contact links with names where applicable using known URLs.
> Use known URLs for contact links

- src/components/providers/EthereumProvider.tsx
Before this change, the following error would occur in the build process:
```
error ReferenceError: localStorage is not defined
at getCachedSnaps (/home/runner/work/snaps-directory/snaps-directory/.cache/page-ssr/routes/webpack:/@metamask/snaps-directory/src/components/providers/EthereumProvider.tsx:62:25)
```
> Check if `localStorage` exists before reading and writing

- .github/workflows/build-lint-test.yml
- gatsby-node.ts
Update cache path to use `node_modules/.cache` instead of `.cache` since the latter is often cleaned by Gatsby.
> Update cache path

- src/components/Layout.tsx
To avoid the website from jumping around too much, we want to always show a scrollbar.
> Always show scrollbar

- .github/workflows/main.yml
- .github/workflows/publish-release.yml
- .github/workflows/republish-release.yml
The message will now tag the Snaps publishers, and send a message in `metamask-snaps`.
> Update Slack subteam and channel

- package.json
- src/Root.tsx
- src/pages/index.tsx
- src/state.ts
- yarn.lock
Closes #95.
This fixes an issue where if you search (or select a category), navigate, and go back, the search query is lost. I've fixed this by storing the search query and selected categories in a Recoil state.
> Persist search query and selected categories

- src/hooks/useSupportedVersion.ts
Instead of checking for a specific version of MetaMask, we now check if any MetaMask provider is detected, and if that provider supports Snaps.
> Update MetaMask detection to support Flask

- src/components/FilterCategory.tsx
- src/components/FilterItem.tsx
- src/components/FilterMenu.tsx
- src/components/SnapCategory.tsx
- src/hooks/index.ts
- src/hooks/useFilter.ts
- src/locales/en/messages.po
- src/pages/index.tsx
- src/state.ts
This pull request changes the filtering behaviour, and adds more filtering options:
- Installed snaps are no longer sorted separately from the other snaps.
- The filter menu now has an option to show only installed snaps.
- Clicking on a category will select only that category.
Closes MetaMask/metamask-planning#1340.
> Add more filtering options

- src/@chakra-ui/gatsby-plugin/theme.js
- src/components/CloseIcon.tsx
- src/components/FilterCategory.tsx
- src/components/FilterMenu.tsx
- src/components/FilterTag.tsx
- src/components/FilterTags.tsx
- src/components/index.ts
- src/hooks/useFilter.ts
- src/hooks/useRecoilReducer.ts
- src/locales/en/messages.po
- src/pages/index.tsx
- src/state.ts
This pull request adds a list of tags based on the current selected filters. It also restores the filtering behaviour to pre-#111.
I've moved some state into a Recoil atom and selector to reduce state duplication, and remove a workaround using `useEffect` which caused bugs.
> Add category tags and update filter behaviour

- src/components/Header.tsx
The header tag is now grey instead of blue, so it doesn't look like the category filter tags.
> Update header tag colours

- src/locales/en/messages.po
- src/pages/{Category.name}/installed.tsx
The `/{category}/installed` page was using the same meta tags as `/{category}` on accident. This fixes that.
> Fix `/{category}/installed` meta tags

- gatsby-node.ts
- src/components/InstallSnapButton.tsx
- src/components/PostInstallModal.tsx
- src/components/SnapCategory.tsx
- src/constants.ts
- src/features/filter/components/FilterCategory.tsx
- src/features/filter/components/FilterTag.tsx
- src/features/filter/store.ts
- src/features/snaps/store.ts
- src/locales/en/messages.po
- src/utils/snaps.ts
Before this, we show "Installed" when a Snap is installed, regardless of whether there are updates available or not. This adds some logic to check if a new version is available, and if so, show an "Update" button, instead of a non-clickable "Installed" button.
> Show update button when a new version is available

- src/@chakra-ui/gatsby-plugin/theme.js
- src/components/InstallSnapButton.tsx
- src/components/InstallUnsupported.tsx
- src/components/InstallUnsupportedDesktop.tsx
- src/components/InstallUnsupportedDesktopUpdate.tsx
- src/pages/snap/{Snap.location}/{Snap.slug}.tsx
Previously, only some buttons had a `_hover` property. I've removed all of these properties and moved it to a theme value instead.
> Add hover to all buttons

- src/theme/global.ts
- src/theme/semantic-tokens.ts
For some reason Chakra wasn't applying the `body` background in light mode. Using a different theme key solves this.
To verify, use `yarn build && yarn serve`, and make sure the colour is applied properly.
> Fix body background regression

- src/components/Header.tsx
The header was rendering on top of the modal background (i.e., when a Snap is installed). To fix this, I've changed it to use a proper [theme value for the z-index](https://chakra-ui.com/docs/styled-system/theme#z-index-values).
> Use theme value for header z-index

- src/components/Logo.tsx
On Safari there was margin around the logo. Forcing the width on the box solves it.
> Fix margin around logo on Safari

- .yarn/patches/@noble-hashes-npm-1.3.2-1e619f9da0.patch
- package.json
- src/analytics.test.ts
- src/analytics.ts
- src/components/InstallSnapButton.test.tsx
- src/components/PostInstallModal.test.tsx
- src/components/PostInstallModal.tsx
- src/components/PostInstallSnapWebsiteButton.test.tsx
- src/components/PostInstallSnapWebsiteButton.tsx
- src/components/SnapWebsiteButton.test.tsx
- src/components/SnapWebsiteButton.tsx
- src/components/index.ts
- src/features/snaps/api.test.ts
- src/features/snaps/api.ts
- src/features/snaps/store.test.ts
- src/features/snaps/store.ts
- src/locales/en/messages.po
- src/pages/snap/{Snap.location}/{Snap.slug}.tsx
- src/types/globals.d.ts
- src/utils/errors.test.ts
- src/utils/errors.ts
- src/utils/index.ts
- yarn.lock
This implements custom events for Segment. Right now the following events are supported:
- `Snap Install Clicked`: When the user clicks on the "Add to MetaMask" button.
- `Snap Installed`: When a Snap is installed (or updated) without errors.
- `Snap Installation Failed`: When a Snap failed installation for an unknown reason.
- `Snap Installation Rejected`: When the user rejected the Snap installation.
- `Snap Update Clicked`: When the user clicks on the "Update Snap" button.
- `Snap Website Clicked`: When the user clicks on the Snap website (either in the installation modal, or on the Snap page).
> Implement custom Segment events

- src/features/filter/Filter.tsx
- src/features/filter/components/FilterOrder.test.tsx
- src/features/filter/components/FilterOrder.tsx
- src/features/filter/constants.tsx
- src/features/filter/store.test.ts
- src/features/filter/store.ts
- src/locales/en/messages.po
This adds a new "Sort" option to the filter menu, which determines how Snaps on the main page are shown. Either in random order (default) or alphabetical.
Closes #144.
> Add sort option to filter menu

- src/features/filter/components/FilterSearch.tsx
- src/types/vendor/react-use-fusejs.d.ts
This increases the search distance from 100 to 300, which helps to find better or more results in certain cases.
> Increase search distance

- yarn.lock
Bump `sharp` to address https://github.com/MetaMask/snaps-directory/security/dependabot/6
Dependabot failed to make this PR itself.
> Bump `sharp`

- src/features/filter/Filter.tsx
- src/features/filter/components/FilterOrder.test.tsx
- src/features/filter/constants.tsx
- src/features/filter/store.test.ts
- src/features/filter/store.ts
- src/locales/en/messages.po
Sort by popularity as default as an experiment. Also disables random ordering in the menu for now too.
> Sort by popularity as default

- .github/workflows/main.yml
- .github/workflows/publish-staging-site.yml
- .github/workflows/publish-staging.yml
- README.md
- gatsby-config.ts
- gatsby-node.ts
- src/pages/snap/{Snap.location}/{Snap.slug}.tsx
This changes the workflows to publish a staging site to a separate repo (MetaMask/snaps-directory-staging). The main branch will be accessible from `https://metamask.github.io/snaps-directory-staging/main`, and every PR will be available from `https://metamask.github.io/snaps-directory-staging/pr/<number>`.
> Publish staging site to separate repo

- .github/workflows/publish-staging-site.yml
- gatsby-config.ts
- gatsby-node.ts
- src/features/filter/store.test.ts
- src/features/filter/store.ts
- src/utils/test-utils/queries.ts
Show uncategorized snaps on the explore page in the staging environment.
Also renames the `STAGING` environment variable to `GATSBY_STAGING`.
> Show uncategorized snaps in staging

- gatsby-config.ts
- src/__mocks__/gatsby.tsx
- src/pages/404.tsx
- src/pages/explore.tsx
- src/pages/index.tsx
This fixes the SEO banners in the staging environment. The site URL as previously always set to `snaps.metamask.io`, and some banner URLs weren't being prefixed properly.
> Fix banners in staging

- src/features/snaps/FilteredSnaps.tsx
This fixes the alignment of the Snap cards in the grid, so they align with the key lines.
> Fix grid alignment

- src/features/snaps/components/SnapCardImage.tsx
Makes `SnapCardImage` use the same fallback color as `SnapAvatar`, removing weird red colored background when loading.
Fixes #267
> Fix fallback background for `SnapCardImage`

- src/pages/index.tsx
This moves the account management category to the top (just below the most popular) on the index page.
> Move account management category to the top on index page

- .github/workflows/crowdin.yml
- crowdin.yml
- lingui.config.ts
This sets up the Crowdin GitHub action for synchronising the translations with Crowdin. The configuration is mostly the same as the one used in the extension.
> Set up Crowdin translations

- src/features/snap/permissions.test.tsx
- src/features/snap/permissions.tsx
- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/locales/ja-JP/messages.po
- src/locales/pt-BR/messages.po
- src/locales/ru-RU/messages.po
- src/locales/tr-TR/messages.po
- src/locales/zh-CN/messages.po
One of the permission descriptions was using `$1`, which was a leftover from copying from the extension. This replaces it with "the requested network" which is consistent with the other permissions.
> Fix translation in permission

- src/store/api.test.ts
- src/types/globals.d.ts
- src/utils/snaps.test.ts
- src/utils/snaps.ts
Adds support for detecting the MetaMask provider via EIP-6963 if the existing logic fails. This in turn makes snaps installable in browsers where multiple wallets are fighting to inject `window.ethereum`.
The site will still prefer `window.ethereum` for now as it is instant and use EIP-6963 as a fallback, this may change in the future.
Closes https://github.com/MetaMask/snaps-directory/issues/280
> Add EIP-6963 support

- src/features/banner/Banner.tsx
- src/features/banner/components/create-snap-banner/CreateSnapBanner.tsx
This moves the FAQ banner to be the last one in the list, and updates the link on the create banner.
> Update banner link and ordering

- gatsby-node.ts
Tweak popularity calculation by only counting the last week of downloads and exclusively counting versions of the package that has been put on the allowlist.
> Tweak popularity calculation

- .yarn/patches/@chakra-ui-focus-lock-npm-2.1.0-46e41f49ee.patch
- package.json
- src/components/InstallUnsupportedDesktop.tsx
- src/components/PostInstallModal.tsx
- src/features/snap/components/MetadataModal.tsx
- src/features/snap/components/Screenshots.tsx
- yarn.lock
This PR does two things to improve the modal behavior: 
- Firstly it enables `preserveScrollBarGap`, this is supposed to be enabled by default in Chakra according to the documentation, but isn't. This prevents the page jumping around when modals are opened.
- Secondly it patches `@chakra-ui/focus-lock` to prevent scrolling when returning focus (e.g. when closing a modal). Chakra uses `react-focus-lock` under the hood which supports not scrolling, but this functionality is not currently supported in Chakra.
> Improve modal behavior

- gatsby-node.ts
- src/constants.ts
- src/features/filter/Filter.test.tsx
- src/features/filter/components/FilterCategory.test.tsx
- src/features/filter/components/FilterTag.test.tsx
- src/features/filter/components/FilterTags.test.tsx
- src/features/filter/constants.tsx
- src/features/filter/store.test.ts
- src/features/snap/components/Category.test.tsx
- src/pages/index.tsx
- src/pages/{Category.name}/index.tsx
- src/pages/{Category.name}/installed.tsx
- src/utils/test-utils/queries.ts
Add support for migrating between the legacy and new category names. This effectively allows Snaps to use either a legacy category name or a new one without breaking the app. The legacy category names are replaced using a mapping a build time, but the keeps the URLs for the legacy categories alive. The legacy URLs redirect to the new category page.
Also actually changes the underlying constants for the categories.
> Change category names

- .github/workflows/build-lint-test.yml
- .github/workflows/create-release-pr.yml
- .github/workflows/main.yml
- .github/workflows/publish-release.yml
- .github/workflows/publish-site.yml
- .github/workflows/publish-staging-site.yml
- .github/workflows/republish-release.yml
This bumps a bunch of GitHub Actions to the latest versions, and also removes the need for `PUBLISH_PAGES_TOKEN` in favour of using OIDC for deployment to GitHub Pages.
> Update GitHub Actions to latest versions and use OIDC for deploying

- gatsby-node.ts
- src/components/SnapsProvider.tsx
- src/features/filter/sort.ts
- src/features/filter/store.test.ts
- src/features/snaps/store.ts
- src/utils/test-utils/queries.ts
Use data endpoint for installation numbers, which should give more accurate installation numbers compared to relying on NPM.
> Use data endpoint for installation numbers

- src/features/snap/components/MetadataModal.tsx
- Hide the audit field if `audits` are omitted or an empty array
- Hide the sourceCode field if omitted
> Hide omitted fields

- src/components/InstallationCount.test.tsx
- src/components/InstallationCount.tsx
- src/features/snap/components/MetadataModal.tsx
- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/locales/ja-JP/messages.po
- src/locales/pt-BR/messages.po
- src/locales/ru-RU/messages.po
- src/locales/tr-TR/messages.po
- src/locales/zh-CN/messages.po
Add installation numbers to the metadata modal as well.
Fixes #379
> Show install numbers in modal

- gatsby-node.ts
Use production endpoint for stats which is more frequently updated.
> Use production endpoint for stats

- src/features/snaps/FilteredSnaps.tsx
Memoize `FilteredSnaps` to prevent an issue where `RelatedSnaps` would change when the Snap profile page re-rendered.
> Memoize `FilteredSnaps`

- src/components/InstallSnapButton.test.tsx
- src/components/InstallSnapButton.tsx
- src/features/filter/store.test.ts
- src/features/filter/store.ts
- src/features/notifications/components/NotificationAcknowledger.test.tsx
- src/features/notifications/components/NotificationsButton.test.tsx
- src/features/notifications/components/NotificationsList.test.tsx
- src/features/notifications/store.test.ts
- src/features/snap/components/Authorship.tsx
- src/features/snaps/api.test.ts
- src/features/snaps/api.ts
- src/features/snaps/components/SnapCard.tsx
- src/features/snaps/store.test.ts
- src/features/snaps/store.ts
- src/hooks/useSupportedVersion.test.ts
- src/pages/snap/{Snap.location}/{Snap.slug}.tsx
- src/store/api.test.ts
- src/store/store.ts
- src/utils/snaps.test.ts
- src/utils/snaps.ts
Closes [#1896](https://github.com/MetaMask/MetaMask-planning/issues/1896)
Swapping out `wallet_getSnaps` for `wallet_getAllSnaps` so that the directory doesn't need permission to get a list of the currently installed snaps. `wallet_revokePermissions` is invoked to remove the directory's `wallet_snap` permission on every install.
> Use `wallet_getAllSnaps` and revoke permissions post-install

- src/components/InstallSnapButton.test.tsx
- src/features/notifications/components/NotificationAcknowledger.test.tsx
- src/features/notifications/components/NotificationsButton.test.tsx
- src/features/notifications/components/NotificationsList.test.tsx
- src/features/snaps/api.test.ts
- src/features/snaps/api.ts
- src/hooks/useSupportedVersion.test.ts
- src/utils/snaps.test.ts
Detecting of installed Snaps is currently broken due to a mismatch in expectation of the return value for `wallet_getAllSnaps`. The RPC method currently returns an array while the site expects an object. This PR fixes this by transforming the array to an object once received.
> fix: Handle actual response type for `wallet_getAllSnaps`

- src/features/snaps/api.ts
After #448, there were some build errors, at least in CI. This adds some validation to make sure `snaps` is defined before trying to process it.
> Fix build errors

- src/components/InstallUnsupportedMobile.tsx
- src/features/banner/components/explore-banner/ExploreBanner.test.tsx
- src/features/banner/components/explore-banner/ExploreBanner.tsx
- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/locales/ja-JP/messages.po
- src/locales/pt-BR/messages.po
- src/locales/ru-RU/messages.po
- src/locales/tr-TR/messages.po
- src/locales/zh-CN/messages.po
Snaps are no longer an open beta and thus the messaging has been removed
fixes https://github.com/MetaMask/MetaMask-planning/issues/2963
> Removed open beta messaging

- .github/workflows/publish-release.yml
- .github/workflows/republish-release.yml
This updates the publish workflows to send a Slack message in `metamask-snaps-deployments`.
> Use `metamask-snaps-deployments` channel for deployment messages

- src/pages/index.tsx
Re-order categories on the landing page to show name resolution Snaps at the top.
> chore: Re-order categories on the landing page

- src/components/Banner.tsx
- src/components/FooterLinks.tsx
- src/components/InstallUnsupportedDesktopUpdate.tsx
- src/features/banner/components/faq-banner/FaqBanner.tsx
This PR updates links to `support.metamask.io` that are, at this point, ~9 months deprecated.
Maintaining the redirects is getting impossible.
These paths should be redirected to, in the future, in case of any further changes; we also intend to make an internal npm package to serve as a single source of truth for MM website resources in product.
Solves [this bug](https://github.com/MetaMask/metamask-extension/issues/29644), along with [this](https://github.com/Consensys/docs-mm-helpcenter/pull/590).
> Update MM Support links to paths current as of January 9, 2025

- gatsby-config.ts
This updates the search functionality to use weights. The Snap name is now the most important part used in the search, followed by the Snap ID, and lastly the summary and description.
> Add weights to search keys

- src/components/InstallSnapButton.test.tsx
- src/hooks/useSupportedVersion.test.ts
- src/utils/snaps.test.ts
- src/utils/snaps.ts
This change only affects staging. It replaces `wallet_getAllSnaps` with `wallet_getSnaps` when detecting the Ethereum provider (`window.ethereum`). `wallet_getAllSnaps` is allowlisted based on the origin, but the staging URL is not on this allowlist. We can use `wallet_getSnaps` to reliably detect if the provider supports Snaps though, and this works in the staging environment as well.
> Update provider detection to use `wallet_getSnaps`

- src/components/FooterLinks.tsx
- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/locales/ja-JP/messages.po
- src/locales/pt-BR/messages.po
- src/locales/ru-RU/messages.po
- src/locales/tr-TR/messages.po
- src/locales/zh-CN/messages.po
Remove feedback link as the URL will stop working soon.
Closes https://github.com/MetaMask/snaps-directory/issues/545
> fix: Remove feedback link

- package.json
- yarn.lock
This bumps `express` from `4.19.2` to `4.21.2`, to resolve the following Dependabot alerts:
- https://github.com/MetaMask/snaps-directory/security/dependabot/27
- https://github.com/MetaMask/snaps-directory/security/dependabot/28
- https://github.com/MetaMask/snaps-directory/security/dependabot/29
- https://github.com/MetaMask/snaps-directory/security/dependabot/31
> Bump `express` from `4.19.2` to `4.21.2`

- yarn.lock
This bumps `msgpackr` from `1.9.7` to `1.11.4` to resolve this Dependabot alert: https://github.com/MetaMask/snaps-directory/security/dependabot/8
> chore(dev-deps): Bump `msgpackr` from `1.9.7` to `1.11.4`

- yarn.lock
This bumps `brace-expansion` from `2.0.1` to `2.0.2` to resolve this Dependabot alert: https://github.com/MetaMask/snaps-directory/security/dependabot/52
> Bump `brace-expansion` from `2.0.1` to `2.0.2`

- package.json
- yarn.lock
This bumps `es5-ext` from `0.10.62` to `0.10.64` to resolve this Dependabot alert: https://github.com/MetaMask/snaps-directory/security/dependabot/13
> chore(dev-deps): Bump `es5-ext` from `0.10.62` to `0.10.64`

- package.json
- yarn.lock
This bumps `ws` from `8.11.0` to `8.17.1` to resolve this Dependabot alert: https://github.com/MetaMask/snaps-directory/security/dependabot/21
> chore(dev-deps): Bump `ws` from `8.11.0` to `8.17.1`
